<a href="https://colab.research.google.com/github/jrigottiedu/TT_26109_repo_notebooks_pipeline/blob/main/Clase_3_Cargar_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📥 Cargar datasets (entry point) en un Notebook

Antes de comenzar a analizar datos, el primer paso es cargar el dataset en nuestro entorno de trabajo (Notebook en Google Colab).

En Python, esto lo hacemos generalmente utilizando la librería Pandas, que nos permite trabajar con la estructuras de datos `DataFrames` que presentamos en la Clase 2.

Existen varias formas de cargar datasets en un notebook, comencemos a ver algunas:

# 1. Cargar un dataset subido al Notebook

Primero debemos subir el archivo .csv o .xlsx al entorno del notebook (carpeta en el menú lateral) y luego podemos cargarlo fácilmente con el método read_csv de pandas: `pd.read_csv`

Nota 1: si el archivo no está previamente subido al entorno, retorna error.

Nota 2: el archivo se elimina cuando Google reinicia la Máquina Virtual sobre la que se está ejecutando el Notebook.

In [ ]:
# Importar la librería Pandas
import pandas as pd

In [ ]:
# pd.read_csv recibe el nombre del archivo y retorna un dataframe
df = pd.read_csv('tips.csv')

In [ ]:
# Visualizamos los primeros registros del dataframe
df.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

# 2. Cargar un dataset usando el link del archivo compartido de Google Drive

Si tenemos un archivo .csv en una carpeta de nuestro Google Drive, primero compartimos sólo ese archivo en modo lectura y copiamos el link o enlace.

Luego usamos el siguiente código para importarlo como Dataframe en este Notebook

In [ ]:
# Importar la librería Pandas
import pandas as pd

In [ ]:
# Link generado al compartir el archivo
link = "https://drive.google.com/file/d/1DjuuUbTYIOkluqs3xM07-lYbs8bCqLpN/view?usp=drive_link"

# Usamos regex para extraer el file_id del link
file_id = link.split('/d/')[1].split('/')[0]

# Con ese file_id generamos la url
url = f"https://drive.google.com/uc?id={file_id}"

# Finalmente lo importamos usando el método read_csv() con la url generada
df = pd.read_csv(url)
df.head()

,id,Empresa,Fecha,Calificación,Comentarios
0,1,Mitchell Group,11/12/2024,1.0,Integer ac leo. Pellentesque ultrices mattis o...
1,2,Kuhn-Fay,25/01/2024,4.0,Vestibulum ac est lacinia nisi venenatis trist...
2,3,Moen-Blick,11/11/2024,3.0,Aliquam quis turpis eget elit sodales sceleris...
3,4,McDermott Inc,01/12/2024,1.0,NaN
4,5,Keebler Inc,12/01/2024,4.0,Integer ac leo. Pellentesque ultrices mattis o...

# 3. Cargar un dataset almacena en tu Google Drive usando la ruta al archivo

Otra opción es acceder a  los archivos guardados en nuestro Google Drive. Como en un Linux, primero debemos montar la unidad (confirmar permisos en el Pop-up) y luego indicar la ruta.

Para obtener la ruta, se puede navegar en menú lateral y luego copiarla desde los 3 puntos.

**Recomendación**: para evitar rutas extensas, crear una carpeta con el nombre `datasets` en el raíz de la unidad y subir ahi los archivos.

In [ ]:
# Montar la unidad
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# importar Pandas
import pandas as pd

In [ ]:
# pd.read_csv recibe la "ruta + nombre_archivo" y retorna un dataframe
df = pd.read_csv('/content/drive/MyDrive/datasets/tips.csv')
df.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

# 4. Cargar un dataset usando el link del Spreadsheet compartido

También podemos trabajar directamente con datos alojados en un Spreadsheet de Google Sheets, lo cual es muy útil cuando compartimos datasets entre varias personas.

Para hacerlo, necesitamos el link del archivo y asegurarnos de que esté configurado como público o con acceso de lectura.

* Paso 1: Obtener el identificador del archivo (eventualmente además el identificador de la hoja)

Si tenés un link como este:
`https://docs.google.com/spreadsheets/d/1FRLM9E7W4VVWEP_sx9QWq2w0okWfbGJ3IWFFXRL0-70/edit?gid=1937180264#gid=1937180264`

Debés transformarlo a:
`https://docs.google.com/spreadsheets/d/ID_DEL_DOC/export?format=csv`

reemplazando, en este caso, `ID_DEL_DOC` por
`1FRLM9E7W4VVWEP_sx9QWq2w0okWfbGJ3IWFFXRL0-70`

* Paso 2: generar la URL al archivo
`https://docs.google.com/spreadsheets/d/1FRLM9E7W4VVWEP_sx9QWq2w0okWfbGJ3IWFFXRL0-70/export?format=csv`

* Paso 3: si necesitas acceder a una hoja que no sea la primera, entonces a la URL agregas el identificador de la hoja con el & `&gid=1937180264 `

In [ ]:
# importar Pandas
import pandas as pd

In [ ]:
url = 'https://docs.google.com/spreadsheets/d/1FRLM9E7W4VVWEP_sx9QWq2w0okWfbGJ3IWFFXRL0-70/export?format=csv&gid=1937180264'
df = pd.read_csv(url)

In [ ]:
df.head(3)

  total_bill    tip   sex smoker  day    time  size
0      50,81  10.00  Male    Yes  Sat  Dinner     3
1      48,33   9.00  Male     No  Sat  Dinner     4
2      48,27   6.73  Male     No  Sat  Dinner     4